spring.application.name=sportsapp

spring.datasource.url=jdbc:postgresql://localhost:5432/sportsapp
spring.datasource.username=postgres
spring.datasource.password=reno123

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.archive.autodetection=class

server.port=8080
